### ISSUE TITLE
Grove CO2 & Temperature & Humidity Sensor SCD41に対応してほしい

### ISSUE THREAD

**Issue by cherenkov** [SeeedJP/Wio_Link#9]
wio nodeでGrove CO2 & Temperature & Humidity Sensor SCD41に対応してほしいです。
https://wiki.seeedstudio.com/Grove-CO2_&_Temperature_&_Humidity_Sensor-SCD41/
ご検討よろしくお願いします

**Comment by matsujirushi** [comment]
https://github.com/SeeedJP/Grove_Drivers_for_Wio/commit/25971ed1720a52c63569a9bf7fc73d6ae844808b

**Comment by matsujirushi** [comment]
日本Wioサーバーにリリース完了。
2022/7/8 13:33
